---
- hosts: all
  connection: local
  strategy: debug
  vars:
    all_home_directory: '{{ ansible_env.HOME }}'
    all_roles_path: 'roles/'
    all_git_base_url: 'git@git.internal.REDACTED.ch'

    # The shell name to use (currently supported: bash, zsh)
    all_shell_name: 'bash'

    # The root folder where shell config are stored
    all_shell_config_root: '{{ all_home_directory }}'

    # The specific shell configuration file
    all_shells_config_file:
      bash: .bash_profile
      zsh: .zshrc
  tasks:
    - name: 'Workstation - Custom tasks'
      block:
        - name: Retrieve tasks from env repository temporary place
          stat:
            path: 'my_tasks.yml'
          register: local_tasks_file
          tags:
            - custom

        - name: Execute custom tasks from temporary env repository
          include_tasks: '{{ local_tasks_file.stat.path }}'
          when: local_tasks_file.stat.exists
          tags:
            - custom
