cask "dropbox"
cask "kdrive"
cask "microsoft-office"

mas "1Password for Safari", id: 1569813296
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
