[tools]
java = "26"
maven = "latest"
node = "latest"
python = "latest"
ruby = "latest"
terraform = "latest"
terragrunt = "latest"
uv = "latest"

"npm:media-archiver" = "latest"
"npm:gs-download" = "latest"
terraform-docs = "latest"
tflint = "latest"
shellcheck = "latest"

[settings]
# Use precompiled Ruby binaries instead of compiling from source
ruby.compile = false
no_hooks = true
# age.strict = false
