---
- hosts: localhost
  connection: local
  strategy: debug
  gather_facts: true
  vars:
    # Define the home directory
    home_directory: "{{ ansible_env.HOME }}"

    # Define the Git user to clone repositories
    git_username: '{{ ansible_user_id | regex_replace("\.", "-") }}_REDACTED'

    # Define the Git email author (ex: configuring git)
    git_email: "{{ ansible_user_id }}@REDACTED.ch"

    # Where git directories will be created
    git_base_directory: "{{ home_directory }}/Documents/repositories"

    # Git directories (to classify various repositories clones)
    git_directories:
      mo: "{{ git_base_directory }}/mo"
      private: "{{ git_base_directory }}/private"
      github: "{{ git_base_directory }}/github"
      github-perso: "{{ git_base_directory }}/github-perso"

    brew_bin_path: "/opt/homebrew/bin"
    brew_bin: "{{ brew_bin_path }}/brew"

  tasks:
    - name: Download Homebrew installer
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
        dest: /tmp/install_homebrew.sh
        mode: "0755"

    - name: Install Homebrew non-interactively
      command: /bin/bash /tmp/install_homebrew.sh
      environment:
        NONINTERACTIVE: "1"
      args:
        creates: "{{ brew_bin_path }}"

    - name: Make it up to date
      shell: "{{ brew_bin }} upgrade"
      register: result
      changed_when: '"Already up-to-date." not in result.stdout'
